### ISSUE TITLE
Stories > Housing 3 - Homelessness data

### ISSUE THREAD

**Issue by LiamOSullivan** [BuildingCityDashboards/bcd-dd-v2.1#323]
Original data source is here, but only in pdf
https://www.homelessdublin.ie/info/figures?type=homeless-families&year=

**Comment by LiamOSullivan** [comment]
Going to manually download the pdfs and scrape the data

**Comment by virtualarchitectures** [comment]
As far as I can see the CSO tables for homelessness [(PEH)](https://statbank.cso.ie/px/pxeirestat/Database/eirestat/Homeless%20in%20Ireland/Homeless%20in%20Ireland_statbank.asp?sp=Homeless%20in%20Ireland&Planguage=0&ProductID=DB_PE) tables discontinued after 2011. After that the 2016 Census has the [E50XX](https://statbank.cso.ie/px/pxeirestat/Database/eirestat/Profile%205%20-%20Homeless%20Persons%20in%20Ireland/Profile%205%20-%20Homeless%20Persons%20in%20Ireland_statbank.asp?sp=Profile%205%20-%20Homeless%20Persons%20in%20Ireland&Planguage=0&ProductID=DB_E5) tables.  Otherwise the Department for Housing, Planning and Local Government have some [historic data and Pdf reports](https://www.housing.gov.ie/housing/homelessness/other/homelessness-data).

**Comment by LiamOSullivan** [comment]
Manually parsed data from pdfs to docs/housing_story_content/homeless_figures_parsed.xlsx
